apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - todo-app-configmap.yaml
  - todo-app-deployment.yaml
  - todo-app-service.yaml

namespace: todo-app 