apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # password (base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # todoapp (base64 encoded)
  POSTGRES_DB: dG9kb2FwcA== 